@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
@file:OptIn(InternalAgentsApi::class)

package ai.koog.agents.core.agent

import ai.koog.agents.core.agent.context.AIAgentContext
import ai.koog.agents.core.agent.entity.AIAgentStrategy
import ai.koog.agents.core.agent.session.AIAgentRunSession
import ai.koog.agents.core.annotation.InternalAgentsApi
import ai.koog.agents.core.feature.pipeline.AIAgentPipeline
import io.github.oshai.kotlinlogging.KLogger
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Abstract base class representing a single-use AI agent with state.
 *
 * This AI agent is designed to execute a specific long-running strategy only once, and provides API to monitor and manage it's state.
 *
 * It maintains internal states including its running status, whether it was started, its result (if available), and
 * the root context associated with its execution. The class enforces safe state transitions and provides
 * thread-safe operations via a mutex.
 *
 * @param Input the type of the input accepted by the agent.
 * @param Output the type of the output produced by the agent.
 * @param TContext the type of the context used during the agent's execution, extending [AIAgentContext].
 * @property logger the logger used for logging execution details and errors.
 * @param id the unique identifier for the agent. Random UUID will be generated if set to null.
 */
public abstract class AIAgentBase<Input, Output, TContext : AIAgentContext> constructor(
    logger: KLogger,
    id: String? = null,
) : AIAgent<Input, Output>() {
    /**
     * Logger instance used for logging messages and events specific to this agent.
     */
    internal open val logger: KLogger = logger

    @OptIn(ExperimentalUuidApi::class)
    final override val id: String by lazy { id ?: Uuid.random().toString() }

    /**
     * The execution strategy defining how the agent processes input and produces output.
     */
    public abstract val strategy: AIAgentStrategy<Input, Output, TContext>

    /**
     * Represents the pipeline used by the AI agent for processing tasks or data.
     *
     * This abstract property defines the structure or sequence of operations
     * within the AI agent's pipeline. It serves as the core mechanism for
     * executing workflows, handling inputs, and generating outputs in the
     * AI agent's functionality.
     */
    @InternalAgentsApi
    public abstract val pipeline: AIAgentPipeline

    /**
     * Executes the agent's main functionality, coordinating with various components
     * such as pipelines and strategies. Ensures the agent is run in a thread-safe
     * manner using locking mechanisms.
     *
     * @param agentInput The input required to execute the agent's strategy.
     *                   This includes any data necessary for processing.
     * @return The output generated by the agent's execution, produced as a
     *         result of applying the strategy to the provided input.
     * @throws IllegalStateException if the agent was already started.
     * @throws Throwable if any exception occurs during the execution process.
     */
    @OptIn(ExperimentalUuidApi::class)
    override suspend fun run(agentInput: Input, sessionId: String?): Output {
        val runId = sessionId ?: Uuid.random().toString()
        val session = AIAgentRunSessionImpl(runId, logger, this, strategy, pipeline, ::prepareContext)
        return session.run(agentInput)
    }

    /**
     * Closes the AI Agent and performs necessary cleanup operations.
     *
     * This method is a suspending function that ensures that the AI Agent's resources are released
     * when it is no longer needed. It notifies the pipeline of the agent's closure and ensures
     * that any associated features or stream providers are properly closed.
     *
     * Overrides the `close` method to implement agent-specific shutdown logic.
     */
    override suspend fun close() {
        // TODO: Delete Closeable interface from [AIAgent] declaration.
    }

    /**
     * Creates a new [AIAgentRunSession] for executing the agent with the given input.
     *
     * This method provides a way to obtain a session object that can be used to execute
     * the agent independently. The session manages the complete execution lifecycle including
     * state tracking, pipeline coordination, and strategy execution.
     *
     * @return A new [AIAgentRunSession] instance configured with this agent's logger, strategy,
     *         and identifier. The session can be used to run the agent with specific input and context.
     */
    @OptIn(ExperimentalUuidApi::class)
    override fun createSession(sessionId: String?): AIAgentRunSession<Input, Output, TContext> {
        val runId = sessionId ?: Uuid.random().toString()
        return AIAgentRunSessionImpl(runId, logger, this, strategy, pipeline, ::prepareContext)
    }

    /**
     * Prepares and initializes the agent context required to handle the given input and run ID.
     *
     * @param agentInput the input provided to the agent for processing.
     * @param runId a unique identifier representing the current execution or operation run.
     * @param eventId a unique identifier for agent-related events.
     * @return the initialized context specific to the agent setup for the provided input and run ID.
     */
    public abstract suspend fun prepareContext(agentInput: Input, runId: String, eventId: String): TContext
}
