@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")

package ai.koog.agents.core.agent

import ai.koog.agents.core.agent.GraphAIAgent.FeatureContext
import ai.koog.agents.core.agent.config.AIAgentConfig
import ai.koog.agents.core.agent.config.MissingToolsConversionStrategy
import ai.koog.agents.core.agent.config.ToolCallDescriber
import ai.koog.agents.core.agent.entity.AIAgentGraphStrategy
import ai.koog.agents.core.feature.AIAgentFunctionalFeature
import ai.koog.agents.core.feature.AIAgentGraphFeature
import ai.koog.agents.core.feature.AIAgentPlannerFeature
import ai.koog.agents.core.feature.config.FeatureConfig
import ai.koog.agents.core.tools.ToolRegistry
import ai.koog.agents.core.utils.BuilderChainAction
import ai.koog.agents.core.utils.ConfigureAction
import ai.koog.agents.planner.AIAgentPlannerStrategy
import ai.koog.agents.planner.AIAgentPlannerStrategyBuilder
import ai.koog.agents.planner.PlannerAIAgent
import ai.koog.agents.planner.TypedAgentPlannerStrategyBuilder
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.executor.model.PromptExecutor
import ai.koog.prompt.llm.LLModel
import kotlinx.datetime.Clock
import kotlin.reflect.KType

/**
 * Represents a configurational builder for setting up and customizing the execution parameters and
 * components of an AI agent. This builder enables fine-grained control over tools, strategies,
 * and prompts utilized by an AI agent during its execution.
 */
public expect class AIAgentBuilder internal constructor() : AIAgentBuilderAPI {
    /**
     * Represents the `PromptExecutor` instance to be utilized within the builder.
     *
     * This variable optionally holds a reference to the configured `PromptExecutor`, which is responsible for:
     * - Executing prompts against language models.
     * - Managing tool interactions for enriched processing.
     * - Handling and processing responses from the language model.
     *
     * If not explicitly set, the builder may rely on a default or alternative mechanism for prompt execution.
     * Primarily used internally to facilitate the construction of instances within the `Builder`.
     */
    @property:PublishedApi
    internal var promptExecutor: PromptExecutor?

    /**
     * Holds the `ToolRegistry` instance used in the builder for managing and organizing tool integrations.
     *
     * This variable defines the tool set available for an AI agent or workflow, enabling its interactions and
     * operations with the registered tools. It is initialized with an empty `ToolRegistry` by default and can
     * be updated during the builder's configuration process.
     */
    @property:PublishedApi
    internal var toolRegistry: ToolRegistry

    /**
     * Internal identifier for the builder instance.
     *
     * This nullable property holds an optional string value that serves as a unique identifier
     * for the builder. It can be set and modified via the corresponding `id` method in the
     * `Builder` class.
     *
     * The identifier is primarily used to distinguish between different instances of the builder
     * configuration, aiding in tracking or debugging processes.
     *
     * Marked as `internal` and annotated with `@PublishedApi` to allow safe internal access for
     * inline functions or other components within the same module.
     */
    @property:PublishedApi
    internal var id: String?

    /**
     * Holds the current `Prompt` instance to be configured within the builder.
     *
     * This variable represents the prompt data utilized by the builder during its setup.
     * It is initialized with an empty prompt by default and can be updated using
     * the `prompt(prompt: Prompt)` method.
     *
     * This property is internal and is intended for use within the builder class.
     */
    @property:PublishedApi
    internal var prompt: Prompt

    /**
     * The `llmModel` variable represents an instance of a Large Language Model (LLM) associated with the builder.
     *
     * This variable holds the configuration or setup of the language model to be*/
    @property:PublishedApi
    internal var llmModel: LLModel?

    /**
     * Represents the temperature setting used to control the randomness of outputs generated by language models.
     *
     * A higher temperature value results in more random and creative outputs, whereas a lower value makes the outputs
     * more focused and deterministic. Common values range between 0.0 and 1.0, but specific use cases might require
     * different ranges. The default value is set to 1.0.
     *
     * This property is intended for internal use by the builder to configure the behavior of the language model
     * during execution.
     */
    @property:PublishedApi
    internal var temperature: Double

    /**
     * Specifies the number of distinct choices or outputs the agent should generate during execution.
     * This value determines the breadth of the agent's response generation process.
     *
     * The default value*/
    @property:PublishedApi
    internal var numberOfChoices: Int

    /**
     * Specifies the strategy to be used for handling missing tool definitions when converting prompts
     * or messages during the building process. This variable determines how tool calls present in the
     * prompt history, but lacking definitions in the current context, are transformed.
     *
     * The default*/
    @property:PublishedApi
    internal var missingToolsConversionStrategy: MissingToolsConversionStrategy

    /**
     * Defines the maximum number of iterations allowed during the execution of a process within the Builder.
     *
     * This property is used to limit the number of execution cycles a certain process can perform, preventing
     * infinite*/
    @property:PublishedApi
    internal var maxIterations: Int

    /**
     * Represents the clock used to determine the current time in the builder.
     * By default, it is set to the system clock, but can be customized for testing or specific time-related behaviors*/
    @property:PublishedApi
    internal var clock: kotlin.time.Clock

    public override fun promptExecutor(promptExecutor: PromptExecutor): AIAgentBuilder

    public override fun llmModel(model: LLModel): AIAgentBuilder

    public override fun toolRegistry(toolRegistry: ToolRegistry): AIAgentBuilder

    public override fun <Input, Output> graphStrategy(
        strategy: AIAgentGraphStrategy<Input, Output>
    ): GraphAgentBuilder<Input, Output>

    public override fun <Input, Output> functionalStrategy(
        strategy: AIAgentFunctionalStrategy<Input, Output>
    ): FunctionalAgentBuilder<Input, Output>

    public override fun <Input, Output> plannerStrategy(
        strategy: AIAgentPlannerStrategy<Input, Output, *>
    ): PlannerAgentBuilder<Input, Output>

    public override fun <Input : Any, Output : Any> plannerStrategy(
        name: String,
        buildStrategy: BuilderChainAction<AIAgentPlannerStrategyBuilder, TypedAgentPlannerStrategyBuilder<Input, Output>>
    ): PlannerAgentBuilder<Input, Output>

    public override fun id(id: String?): AIAgentBuilder

    public override fun systemPrompt(systemPrompt: String): AIAgentBuilder

    public override fun prompt(prompt: Prompt): AIAgentBuilder

    public override fun temperature(temperature: Double): AIAgentBuilder

    public override fun numberOfChoices(numberOfChoices: Int): AIAgentBuilder

    public override fun maxIterations(maxIterations: Int): AIAgentBuilder

    public override fun agentConfig(config: AIAgentConfig): AIAgentBuilder

    public override fun <TConfig : FeatureConfig> install(
        feature: AIAgentGraphFeature<TConfig, *>,
        configure: ConfigureAction<TConfig>
    ): GraphAgentBuilder<String, String>

    public override fun build(): AIAgent<String, String>
}

/**
 * A builder class for creating instances of [AIAgent]. This builder provides a fluent interface
 * to configure various parameters and components required to construct an AI agent with a
 * specific set of features, tools, and execution strategies.
 *
 * @param Input The input type that the agent processes.
 * @param Output The output type that the agent produces.
 * @param strategy The execution strategy used by the agent for processing input and generating results.
 * @param inputType The [KType] representation of the input parameter type.
 * @param outputType The [KType] representation of the output parameter type.
 */
public class GraphAgentBuilder<Input, Output>(
    private val strategy: AIAgentGraphStrategy<Input, Output>,
    private val inputType: KType,
    private val outputType: KType,
    private var promptExecutor: PromptExecutor? = null,
    private var toolRegistry: ToolRegistry = ToolRegistry.EMPTY,
    private var id: String? = null,
    private var prompt: Prompt? = Prompt.Empty,
    private var llmModel: LLModel? = null,
    private var temperature: Double = 1.0,
    private var numberOfChoices: Int = 1,
    private var missingToolsConversionStrategy: MissingToolsConversionStrategy =
        MissingToolsConversionStrategy.Missing(ToolCallDescriber.JSON),
    private var maxIterations: Int = 50,
    private var clock: Clock = kotlin.time.Clock.System,
    private var featureInstallers: MutableList<FeatureContext.() -> Unit> = mutableListOf(),
) {

    /**
     * Sets the `PromptExecutor` instance to be used by this `GraphAgentBuilder`.
     *
     * @param promptExecutor The `PromptExecutor` instance responsible for executing prompts
     *                        and interacting with the language model.
     * @return The current instance of `GraphAgentBuilder` for method chaining.
     */
    public fun promptExecutor(promptExecutor: PromptExecutor): GraphAgentBuilder<Input, Output> = apply {
        this.promptExecutor = promptExecutor
    }

    /**
     * Sets the large language model (LLM) for the agent builder.
     *
     * @param model The `LLModel` instance representing the large language model to be used by the agent.
     * @return The current instance of `GraphAgentBuilder<Input, Output>` for method chaining.
     */
    public fun llmModel(model: LLModel): GraphAgentBuilder<Input, Output> = apply {
        this.llmModel = model
    }

    /**
     * Sets the `toolRegistry` for the `GraphAgentBuilder` and returns the updated builder instance.
     *
     * @param toolRegistry The `ToolRegistry` instance to be associated with the `GraphAgentBuilder`.
     * @return The current instance of `GraphAgentBuilder` with the updated `toolRegistry`.
     */
    public fun toolRegistry(toolRegistry: ToolRegistry): GraphAgentBuilder<Input, Output> = apply {
        this.toolRegistry = toolRegistry
    }

    /**
     * Sets the unique identifier for the `GraphAgentBuilder` instance.
     *
     * @param id The unique identifier to associate with the agent. Can be null if no identifier is required.
     * @return The current instance of `GraphAgentBuilder` with the updated identifier.
     */
    public fun id(id: String?): GraphAgentBuilder<Input, Output> = apply {
        this.id = id
    }

    /**
     * Sets the system-level prompt for the agent.
     *
     * The system prompt provides predefined instructions or context
     * to guide the behavior of the agent.
     *
     * @param systemPrompt The system-level instructions or context for the agent.
     * @return The updated instance of GraphAgentBuilder with the system prompt applied.
     */
    public fun systemPrompt(systemPrompt: String): GraphAgentBuilder<Input, Output> = apply {
        this.prompt = ai.koog.prompt.dsl.prompt(id = "agent") { system(systemPrompt) }
    }

    /**
     * Sets the prompt for the GraphAgentBuilder and returns the builder instance for further configuration.
     *
     * @param prompt The prompt configuration to be set.
     * @return The updated instance of GraphAgentBuilder.
     */
    public fun prompt(prompt: Prompt): GraphAgentBuilder<Input, Output> = apply {
        this.prompt = prompt
    }

    /**
     * Sets the temperature parameter for the AI agent configuration.
     *
     * Temperature controls the randomness of the AI model's output.
     * A higher temperature results in more randomness, while a lower temperature makes the output more deterministic.
     *
     * @param temperature The temperature value to be set, typically ranging between 0.0 and 1.0.
     * @return The current instance of [GraphAgentBuilder], allowing method chaining.
     */
    public fun temperature(temperature: Double): GraphAgentBuilder<Input, Output> = apply {
        this.temperature = temperature
    }

    /**
     * Sets the number of choices the agent can generate and returns the updated builder instance.
     *
     * @param numberOfChoices The number of choices to configure for the agent.
     * @return The updated instance of the GraphAgentBuilder with the specified number of choices.
     */
    public fun numberOfChoices(numberOfChoices: Int): GraphAgentBuilder<Input, Output> = apply {
        this.numberOfChoices = numberOfChoices
    }

    /**
     * Sets the maximum number of iterations allowed for the agent's execution.
     *
     * @param maxIterations The maximum number of iterations to configure.
     * @return The current instance of [GraphAgentBuilder] for method chaining.
     */
    public fun maxIterations(maxIterations: Int): GraphAgentBuilder<Input, Output> = apply {
        this.maxIterations = maxIterations
    }

    /**
     * Configures the `GraphAgentBuilder` using the provided `AIAgentConfig` instance.
     *
     * The configuration sets the prompt, language model, maximum iterations,
     * and the strategy for handling missing tools based on the given `AIAgentConfig`.
     *
     * @param config The `AIAgentConfig` instance containing the agent's configuration,
     *               including prompt settings, model, iteration limits, and tool handling strategies.
     * @return The current instance of `GraphAgentBuilder<Input, Output>` for method chaining.
     */
    public fun agentConfig(config: AIAgentConfig): GraphAgentBuilder<Input, Output> = apply {
        this.prompt = config.prompt
        this.llmModel = config.model
        this.maxIterations = config.maxAgentIterations
        this.missingToolsConversionStrategy = config.missingToolsConversionStrategy
    }

    /**
     * Installs a specified feature into the current context and applies its configuration.
     *
     * @param TConfig The type of configuration required by the feature, extending [FeatureConfig].
     * @param feature The feature to install, represented by an implementation of [AIAgentGraphFeature].
     * @param configure A lambda used to customize the configuration of the feature.
     * @return The current [GraphAgentBuilder] instance, enabling further configurations.
     */
    public fun <TConfig : FeatureConfig> install(
        feature: AIAgentGraphFeature<TConfig, *>,
        configure: ConfigureAction<TConfig>
    ): GraphAgentBuilder<Input, Output> = apply {
        this.featureInstallers += {
            install(feature) {
                configure.configure(this)
            }
        }
    }

    /**
     * Builds and returns an instance of `AIAgent` configured using the parameters
     * provided to the `GraphAgentBuilder`.
     *
     * @return an instance of `AIAgent` initialized with the specified input and output types,
     *         strategy, tool registry, prompt executor, model configuration, and other optional settings.
     */
    public fun build(): AIAgent<Input, Output> {
        return GraphAIAgent(
            inputType = inputType,
            outputType = outputType,
            strategy = strategy,
            promptExecutor = requireNotNull(promptExecutor) { "promptExecutor must be set" },
            toolRegistry = toolRegistry,
            id = id,
            agentConfig = AIAgentConfig(
                prompt = prompt ?: Prompt.Empty,
                model = requireNotNull(llmModel) { "llmModel must be set" },
                maxAgentIterations = maxIterations,
            ),
            clock = clock
        ) {
            featureInstallers.forEach { install ->
                install()
            }
        }
    }
}

/**
 * A builder class for constructing instances of `FunctionalAIAgent` with customizable configuration.
 *
 * This builder simplifies the configuration process by providing a fluent API to set various
 * parameters for the `FunctionalAIAgent`, including its behavior strategy, prompt details, model settings,
 * tool registry, and additional features. The builder enforces the presence of required configurations
 * and allows the addition of optional parameters to tailor the agent's functionality.
 *
 * @param Input The type of input that the resulting AI agent will process.
 * @param Output The type of output that the resulting AI agent will produce.
 * @property strategy The strategy defining the behavior of the AI agent, responsible for the core iterative logic.
 * @property promptExecutor The initial executor responsible for executing prompts, defaults to `null` if not set.
 * @property toolRegistry A registry of tools available to the agent, by default set to `ToolRegistry.EMPTY`.
 * @property id An optional unique identifier for the agent.
 * @property prompt The system prompt or series of prompts defining the agent's conversational context, initialized to `Prompt.Empty`.
 * @property llmModel The model used by the agent for language generation, defaults to `null` if not set.
 * @property temperature The sampling temperature affecting the randomness of outputs, default is `1.0`.
 * @property numberOfChoices The number of choices generated by the model per output, default is `1`.
 * @property missingToolsConversionStrategy A strategy for handling missing tools during execution, default is `MissingToolsConversionStrategy.Missing`.
 * @property maxIterations The maximum number of iterations the agent can perform during execution, default is `50`.
 * @property clock The clock instance used for time-related functionality, default is `Clock.System`.
 * @property featureInstallers A list of feature installation lambdas defining additional functionalities the agent should have.
 */
public class FunctionalAgentBuilder<Input, Output>(
    private val strategy: AIAgentFunctionalStrategy<Input, Output>,
    private var promptExecutor: PromptExecutor? = null,
    private var toolRegistry: ToolRegistry = ToolRegistry.EMPTY,
    private var id: String? = null,
    private var prompt: Prompt? = Prompt.Empty,
    private var llmModel: LLModel? = null,
    private var temperature: Double = 1.0,
    private var numberOfChoices: Int = 1,
    private var missingToolsConversionStrategy: MissingToolsConversionStrategy =
        MissingToolsConversionStrategy.Missing(ToolCallDescriber.JSON),
    private var maxIterations: Int = 50,
    private var clock: Clock = kotlin.time.Clock.System,
    private var featureInstallers: MutableList<FunctionalAIAgent.FeatureContext.() -> Unit> = mutableListOf(),
) {

    /**
     * Sets the provided `PromptExecutor` instance for the current `FunctionalAgentBuilder`.
     *
     * @param promptExecutor The `PromptExecutor` instance to be used for executing prompts.
     * @return The updated `FunctionalAgentBuilder` instance with the specified prompt executor configuration.
     */
    public fun promptExecutor(promptExecutor: PromptExecutor): FunctionalAgentBuilder<Input, Output> = apply {
        this.promptExecutor = promptExecutor
    }

    /**
     * Configures the functional agent builder to use a specific Large Language Model (LLM) for processing.
     *
     * @param model The Large Language Model (LLM) instance to be used, which defines the provider, identifier, and capabilities.
     * @return The updated instance of [FunctionalAgentBuilder] for further configuration chaining.
     */
    public fun llmModel(model: LLModel): FunctionalAgentBuilder<Input, Output> = apply {
        this.llmModel = model
    }

    /**
     * Sets the tool registry to be used by the FunctionalAgentBuilder.
     *
     * @param toolRegistry The ToolRegistry instance to be associated with this builder.
     * @return The current FunctionalAgentBuilder instance to allow method chaining.
     */
    public fun toolRegistry(toolRegistry: ToolRegistry): FunctionalAgentBuilder<Input, Output> = apply {
        this.toolRegistry = toolRegistry
    }

    /**
     * Sets the unique identifier for the FunctionalAgent.
     *
     * @param id The unique identifier as a nullable string. It can be used to reference the agent in various contexts or hierarchies.
     * @return The builder instance, allowing for method chaining during the configuration of the FunctionalAgent.
     */
    public fun id(id: String?): FunctionalAgentBuilder<Input, Output> = apply {
        this.id = id
    }

    /**
     * Sets the system-level prompt for the agent being built.
     * The system-level prompt provides contextual instructions to the agent.
     *
     * @param systemPrompt The message that defines the behavior or context for the agent.
     * @return The instance of FunctionalAgentBuilder with the updated system-level prompt.
     */
    public fun systemPrompt(systemPrompt: String): FunctionalAgentBuilder<Input, Output> = apply {
        this.prompt = ai.koog.prompt.dsl.prompt(id = "agent") { system(systemPrompt) }
    }

    /**
     * Sets the specified prompt for the functional agent being built.
     *
     * @param prompt The prompt to be used by the agent.
     * @return The current instance of FunctionalAgentBuilder with the updated prompt.
     */
    public fun prompt(prompt: Prompt): FunctionalAgentBuilder<Input, Output> = apply {
        this.prompt = prompt
    }

    /**
     * Sets the temperature parameter for the functional agent. Temperature controls the randomness of the
     * agent's outputs, where higher values result in more diverse outputs and lower values result in more focused outputs.
     *
     * @param temperature The temperature value to be used. It should typically range between 0.0 and 1.0.
     * @return The updated instance of the FunctionalAgentBuilder with the temperature parameter set.
     */
    public fun temperature(temperature: Double): FunctionalAgentBuilder<Input, Output> = apply {
        this.temperature = temperature
    }

    /**
     * Configures the number of choices to be considered during the functional agent's operations.
     *
     * @param numberOfChoices The desired number of choices to configure for the functional agent.
     * @return The updated instance of [FunctionalAgentBuilder] configured with the specified number of choices.
     */
    public fun numberOfChoices(numberOfChoices: Int): FunctionalAgentBuilder<Input, Output> = apply {
        this.numberOfChoices = numberOfChoices
    }

    /**
     * Sets the maximum number of iterations for the functional agent builder.
     *
     * @param maxIterations The maximum number of iterations to be set.
     * @return The current instance of FunctionalAgentBuilder with the updated maximum iterations.
     */
    public fun maxIterations(maxIterations: Int): FunctionalAgentBuilder<Input, Output> = apply {
        this.maxIterations = maxIterations
    }

    /**
     * Configures the FunctionalAgentBuilder with the provided AI agent configuration settings.
     *
     * This method applies the specified configuration to the builder, including properties
     * such as the prompt, language model, maximum iterations, and strategy for handling missing tools.
     *
     * @param config The configuration object of type [AIAgentConfig] containing the settings
     *               to be applied to the builder.
     * @return The updated instance of [FunctionalAgentBuilder] for further configuration chaining.
     */
    public fun agentConfig(config: AIAgentConfig): FunctionalAgentBuilder<Input, Output> = apply {
        this.prompt = config.prompt
        this.llmModel = config.model
        this.maxIterations = config.maxAgentIterations
        this.missingToolsConversionStrategy = config.missingToolsConversionStrategy
    }

    /**
     * Installs and configures a given feature into the functional agent builder.
     *
     * @param TConfig the type of the feature configuration, which extends [FeatureConfig].
     * @param feature the feature to be installed, represented by an implementation of [AIAgentFunctionalFeature].
     * @param configure a lambda function to customize the configuration of the feature, where the provided [TConfig] can be modified.
     * @return the current [FunctionalAgentBuilder] instance for chaining further configurations.
     */
    public fun <TConfig : FeatureConfig> install(
        feature: AIAgentFunctionalFeature<TConfig, *>,
        configure: ConfigureAction<TConfig>
    ): FunctionalAgentBuilder<Input, Output> = apply {
        this.featureInstallers += {
            install(feature) {
                configure.configure(this)
            }
        }
    }

    /**
     * Builds and returns an instance of `AIAgent<Input, Output>` based on the current configuration
     * of the `FunctionalAgentBuilder`. This method ensures that all required fields are set,
     * and applies any configured feature installers to the agent.
     *
     * @return an instance of `AIAgent<Input, Output>` created using the provided configuration.
     * @throws IllegalArgumentException if required fields, such as `promptExecutor` or `llmModel`, are not set.
     */
    public fun build(): AIAgent<Input, Output> {
        return FunctionalAIAgent(
            strategy = strategy,
            promptExecutor = requireNotNull(promptExecutor) { "promptExecutor must be set" },
            toolRegistry = toolRegistry,
            id = id,
            agentConfig = AIAgentConfig(
                prompt = prompt ?: Prompt.Empty,
                model = requireNotNull(llmModel) { "llmModel must be set" },
                maxAgentIterations = maxIterations,
            ),
            clock = clock
        ) {
            featureInstallers.forEach { install ->
                install()
            }
        }
    }
}

/**
 * Builds an AI-based planning agent by configuring various parameters and defining custom behaviors
 * for the agent. This builder allows flexible setup of an agent's functionality and behavior
 * based on the provided configuration and tools.
 *
 * @param State The type representing the state handled by the AI agent.
 * @param strategy The planning strategy used by the agent to process and execute tasks.
 * @param promptExecutor The executor responsible for handling AI prompts.
 * @param toolRegistry The registry of tools available for use by the agent. Defaults to an empty tool registry.
 * @param id The optional identifier of the agent.
 * @param prompt The system prompt or structured prompt that the agent uses for planning. Defaults to an empty prompt.
 * @param llmModel The language learning model used by the agent to interpret and process tasks.
 * @param temperature The temperature parameter controlling randomness in the agent's decision-making. Defaults to `1.0`.
 * @param numberOfChoices The number of choices for the agent's output per action. Defaults to `1`.
 * @param missingToolsConversionStrategy The strategy used when dealing with missing tools during execution.
 *        Defaults to converting missing tools to JSON representation.
 * @param maxIterations The maximum number of iterations the agent can perform in a planning loop. Defaults to `50`.
 * @param clock The clock instance used to track time-related operations for the agent. Defaults to the system clock.
 * @param featureInstallers A list of feature installers that enhance the agent's behavior with additional functionality.
 */
public class PlannerAgentBuilder<Input, Output>(
    private val strategy: AIAgentPlannerStrategy<Input, Output, *>,
    private var promptExecutor: PromptExecutor? = null,
    private var toolRegistry: ToolRegistry = ToolRegistry.EMPTY,
    private var id: String? = null,
    private var prompt: Prompt? = Prompt.Empty,
    private var llmModel: LLModel? = null,
    private var temperature: Double = 1.0,
    private var numberOfChoices: Int = 1,
    private var missingToolsConversionStrategy: MissingToolsConversionStrategy =
        MissingToolsConversionStrategy.Missing(ToolCallDescriber.JSON),
    private var maxIterations: Int = 50,
    private var clock: Clock = kotlin.time.Clock.System,
    private var featureInstallers: MutableList<PlannerAIAgent.FeatureContext.() -> Unit> = mutableListOf(),
) {

    /**
     * Sets the `PromptExecutor` instance to be used by the `PlannerAgentBuilder`.
     *
     * @param promptExecutor An instance of `PromptExecutor` that will handle prompt execution logic.
     * @return The current instance of `PlannerAgentBuilder<Input, Output>` for method chaining.
     */
    public fun promptExecutor(promptExecutor: PromptExecutor): PlannerAgentBuilder<Input, Output> = apply {
        this.promptExecutor = promptExecutor
    }

    /**
     * Sets the Large Language Model (LLM) to be used by the `PlannerAgentBuilder`.
     *
     * @param model The instance of [LLModel] representing the Large Language Model to be configured.
     * @return The current instance of [PlannerAgentBuilder] for method chaining.
     */
    public fun llmModel(model: LLModel): PlannerAgentBuilder<Input, Output> = apply {
        this.llmModel = model
    }

    /**
     * Sets the tool registry for the PlannerAgentBuilder.
     *
     * @param toolRegistry The tool registry to be used.
     * @return The PlannerAgentBuilder instance with the updated tool registry.
     */
    public fun toolRegistry(toolRegistry: ToolRegistry): PlannerAgentBuilder<Input, Output> = apply {
        this.toolRegistry = toolRegistry
    }

    /**
     * Sets the identifier for the PlannerAgentBuilder and returns the updated builder instance.
     *
     * @param id The identifier to be set. It can be null.
     * @return The updated PlannerAgentBuilder instance for chaining further configurations.
     */
    public fun id(id: String?): PlannerAgentBuilder<Input, Output> = apply {
        this.id = id
    }

    /**
     * Configures the system prompt for the planner agent.
     *
     * The system prompt provides foundational instructions or context for the planner agent's behavior.
     *
     * @param systemPrompt The content of the system prompt to set.
     * @return The current instance of the PlannerAgentBuilder with the specified system prompt applied.
     */
    public fun systemPrompt(systemPrompt: String): PlannerAgentBuilder<Input, Output> = apply {
        this.prompt = ai.koog.prompt.dsl.prompt(id = "agent") { system(systemPrompt) }
    }

    /**
     * Sets the prompt to be used by the builder and updates the internal state accordingly.
     *
     * @param prompt The prompt to be used by the PlannerAgentBuilder.
     * @return The current instance of PlannerAgentBuilder with the updated prompt.
     */
    public fun prompt(prompt: Prompt): PlannerAgentBuilder<Input, Output> = apply {
        this.prompt = prompt
    }

    /**
     * Sets the temperature parameter for the planner agent.
     * Temperature controls the randomness of the agent's outputs.
     * A higher value encourages more random and diverse outputs,
     * while a lower value makes the outputs more focused and deterministic.
     *
     * @param temperature The temperature value to be used. Typically ranges from 0.0 to 1.0.
     * @return The current instance of [PlannerAgentBuilder], allowing for method chaining.
     */
    public fun temperature(temperature: Double): PlannerAgentBuilder<Input, Output> = apply {
        this.temperature = temperature
    }

    /**
     * Sets the number of choices the planner agent can consider while making decisions.
     *
     * @param numberOfChoices The number of choices to be allowed for the agent.
     * @return The updated instance of the PlannerAgentBuilder.
     */
    public fun numberOfChoices(numberOfChoices: Int): PlannerAgentBuilder<Input, Output> = apply {
        this.numberOfChoices = numberOfChoices
    }

    /**
     * Sets the maximum number of iterations for the planner agent.
     *
     * @param maxIterations The maximum number of iterations the agent is allowed to perform.
     * @return The updated instance of the PlannerAgentBuilder with the specified maximum iterations.
     */
    public fun maxIterations(maxIterations: Int): PlannerAgentBuilder<Input, Output> = apply {
        this.maxIterations = maxIterations
    }

    /**
     * Configures the agent with the specified AI agent configuration.
     *
     * @param config The configuration object that contains settings for the AI agent, such as prompt, model, maximum iterations, and tool conversion strategy.
     * @return The updated instance of PlannerAgentBuilder<Input, Output> with the applied configuration.
     */
    public fun agentConfig(config: AIAgentConfig): PlannerAgentBuilder<Input, Output> = apply {
        this.prompt = config.prompt
        this.llmModel = config.model
        this.maxIterations = config.maxAgentIterations
        this.missingToolsConversionStrategy = config.missingToolsConversionStrategy
    }

    /**
     * Installs a functional feature into the PlannerAgentBuilder with the specified configuration.
     *
     * @param feature The functional feature to be installed, parameterized with a configuration type and an additional type.
     * @param configure A lambda or action responsible for configuring the provided feature with the appropriate settings.
     * @return The current instance of PlannerAgentBuilder with the feature installed, enabling method chaining.
     */
    public fun <TConfig : FeatureConfig> install(
        feature: AIAgentPlannerFeature<TConfig, *>,
        configure: ConfigureAction<TConfig>
    ): PlannerAgentBuilder<Input, Output> = apply {
        this.featureInstallers += {
            install(feature) {
                configure.configure(this)
            }
        }
    }

    /**
     * Constructs and returns an instance of [AIAgent] configured with the provided parameters and features.
     *
     * @return An instance of [AIAgent] that uses the specified strategy, model, prompt, tools, and other configurations defined in the builder.
     */
    public fun build(): AIAgent<Input, Output> {
        return PlannerAIAgent(
            strategy = strategy,
            promptExecutor = requireNotNull(promptExecutor) { "promptExecutor must be set" },
            toolRegistry = toolRegistry,
            id = id,
            agentConfig = AIAgentConfig(
                prompt = prompt ?: Prompt.Empty,
                model = requireNotNull(llmModel) { "llmModel must be set" },
                maxAgentIterations = maxIterations,
            ),
            clock = clock
        ) {
            featureInstallers.forEach { install ->
                install()
            }
        }
    }
}
